import { BranchContext } from '@/foundation/BranchContext';
import {
    ServiceDefinition,
    ServicesFile,
    GeneratedService,
    GeneratedServicesFile,
    RepositoryServices,
    RepoServices,
} from '@/foundation/types/Services';
import { pathExists, writeTextFile, readJSONFile } from './fs';
import { validateInput } from './validator';
import { ForgePortNotAssignedError, ForgeServicesScanError, ForgeServicesValidationError } from '@/foundation/errors';
import { RepoPortMappings } from '@/foundation/PortAllocator';
import path from 'path';
import { slugify } from './slug';
import { FEAT_FORGE_SERVICES_FILE } from './constants';

export interface ScannedServices {
    repos: RepoServices;
}

/**
 * Scan all repositories in a branch for .forge/services.json files
 */
export async function scanServices(branchContext: BranchContext): Promise<ScannedServices> {
    const repos: RepoServices = {};

    for (const repo of branchContext.repositories) {
        const servicesPath = repo.getRepoConfigPath(FEAT_FORGE_SERVICES_FILE);

        if (!(await pathExists(servicesPath))) {
            // Repo has no services file, skip it
            continue;
        }

        try {
            const servicesFile = await readJSONFile(ServicesFile, servicesPath);
            repos[repo.name] = servicesFile.services;
        } catch (error) {
            if (error instanceof Error) {
                console.error(error);
                throw new ForgeServicesScanError(`Failed to scan services from ${repo.name}: ${error.message}`);
            }
            throw error;
        }
    }

    return { repos };
}

/**
 * Validate a service definition
 */
export async function validateServiceDefinition(service: ServiceDefinition): Promise<void> {
    try {
        await validateInput(ServiceDefinition, service);
    } catch (error) {
        if (error instanceof Error) {
            throw new ForgeServicesValidationError(error.message);
        }
        throw error;
    }
}

/**
 * Generate and write generated.services.json with port assignments
 */
export async function generateRootServicesFile(
    branchRootPath: string,
    scannedServices: ScannedServices,
    portMappings: RepoPortMappings,
): Promise<GeneratedServicesFile> {
    const generatedFile = new GeneratedServicesFile();
    generatedFile._doNotEdit = "This file is auto-generated by 'forge services scan'. Manual edits will be lost on next generation.";
    generatedFile.generatedAt = new Date().toISOString();
    generatedFile.repos = {};

    for (const [repoName, services] of Object.entries(scannedServices.repos)) {
        const repoPortMappings = portMappings[repoName] || {};
        const generatedServices: GeneratedService[] = [];

        for (const service of services) {
            const generatedService = new GeneratedService();
            Object.assign(generatedService, service);
            generatedService.port = repoPortMappings[service.name];

            if (!generatedService.port) {
                throw new ForgePortNotAssignedError(`No port allocated for service "${service.name}" in repo "${repoName}"`);
            }

            generatedServices.push(generatedService);
        }

        const repoServices = new RepositoryServices();
        repoServices.services = generatedServices;
        generatedFile.repos[repoName] = repoServices;
    }

    // Write to file
    const filePath = path.join(branchRootPath, 'generated.services.json');
    const content = JSON.stringify(generatedFile, null, 2);
    await writeTextFile(filePath, content);

    return generatedFile;
}

/**
 * Generate and write .envrc with service environment variables
 */
export async function generateEnvrcFile(
    branchRootPath: string,
    branchName: string,
    generatedServices: GeneratedServicesFile,
    branchAllocationRange?: { start: number; end: number },
    proxyPort: number = 8080,
): Promise<string> {
    const branchSlug = slugify(branchName);
    const timestamp = new Date().toISOString();

    const lines: string[] = [];

    // Header
    lines.push('# ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY');
    lines.push(`# This file is generated by 'forge env update' at ${timestamp}`);
    lines.push("# Any manual edits will be lost on the next 'forge env update' run");
    lines.push('');

    // Branch configuration
    lines.push('# Branch configuration');
    lines.push(`export BRANCH_SLUG="${branchSlug}"`);
    lines.push('export BRANCH_SERVICES_CONFIG="generated.services.json"');
    lines.push('');

    // Services ports
    if (branchAllocationRange) {
        lines.push(`# Services ports (branchRoot: ${branchAllocationRange.start}-${branchAllocationRange.end})`);
    } else {
        lines.push('# Services ports');
    }

    for (const [repoName, repoServices] of Object.entries(generatedServices.repos)) {
        lines.push(`# ${repoName}`);

        for (const service of repoServices.services) {
            const serviceSlug = slugify(service.name, false, true); // Don't allow slashes or hyphens in service slug to keep env var names clean
            // Format: REPO_NAME_SERVICE_NAME_PORT
            // const envName = `${repoName.toUpperCase()}_${service.name.toUpperCase()}`; // Trying to not use the repo name for now, see if it's needed later
            const envName = `FEAT_FORGE_${serviceSlug.toUpperCase()}`; // Prefix with FEAT_FORGE_ to avoid potential conflicts with existing env vars, and since these are forge-specific
            lines.push(`export ${envName}_PORT=${service.port}`);
            lines.push(`export ${envName}_PROXY_URL=${service.type}://${branchSlug}.${serviceSlug}.localhost:${proxyPort}`);
            lines.push(`export ${envName}_DIRECT_URL=${service.type}://localhost:${service.port}`);

            if (service.path) {
                lines.push(`export ${envName}_PATH="${service.path}"`);
            }
        }
        lines.push('');
    }

    // Forge proxy configuration (for future use)
    lines.push('# Forge proxy configuration (for future use)');
    lines.push('export FORGE_PROXY_ENABLED=true');
    lines.push(`export FORGE_PROXY_PORT=${proxyPort}`);
    lines.push('');

    const content = lines.join('\n');

    // Write to file
    const filePath = path.join(branchRootPath, '.envrc');
    await writeTextFile(filePath, content);

    return content;
}
