import { BranchContext } from '@/foundation/BranchContext';
import { ForgeServicesScanError } from '@/foundation/errors';
import { ForgeContext } from '@/foundation/ForgeContext';
import { PortAllocator } from '@/foundation/PortAllocator';
import { GeneratedServicesDTO, RepositoryServices, ServiceDefinitionWithPort, ServicesDTO } from '@/foundation/types/Services';
import { FEAT_FORGE_GENERATED_SERVICES_FILE, FEAT_FORGE_SERVICES_FILE } from './constants';
import { pathExists, readJSONFile, writeTextFile } from './fs';
import { slugify } from './slug';
import { ForgeError } from '@/foundation/errors/ForgeError';

/**
 * Scan all repositories in a branch for .forge/services.json files
 */
export async function scanReposServices(branchContext: BranchContext): Promise<RepositoryServices[]> {
    const repositories: RepositoryServices[] = [];

    for (const repo of branchContext.repositories) {
        const servicesFilePath = repo.getRepoConfigPath(FEAT_FORGE_SERVICES_FILE);

        if (!(await pathExists(servicesFilePath))) {
            // Repo has no services file, skip it
            continue;
        }

        try {
            const servicesFile = await readJSONFile(ServicesDTO, servicesFilePath);
            repositories.push({ name: repo.name, services: servicesFile.services });
        } catch (error) {
            throw ForgeServicesScanError.extend(error, `Failed to scan services from ${repo.name} at ${servicesFilePath}`);
        }
    }

    return repositories;
}

/**
 * Generate and write generated.services.json with port assignments
 */
export async function generateBranchServicesFile(
    branchContext: BranchContext,
    portAllocator: PortAllocator,
): Promise<{ path: string; services: ServiceDefinitionWithPort[] }> {
    const branchPortAllocation = portAllocator.getAllocation(branchContext.branchName);

    let services: ServiceDefinitionWithPort[] = [];

    if (branchPortAllocation) {
        services = branchPortAllocation.getServices();
    }
    const generatedFile: GeneratedServicesDTO = {
        _doNotEdit: "This file is auto-generated by 'forge services scan'. Manual edits will be lost on next generation.",
        generatedAt: new Date(),
        services,
    };

    const filePath = branchContext.getInPath(FEAT_FORGE_GENERATED_SERVICES_FILE);
    const content = JSON.stringify(generatedFile, null, 2);
    await writeTextFile(filePath, content);

    return { path: filePath, services };
}

export async function loadGeneratedServicesFile(branchContext: BranchContext): Promise<GeneratedServicesDTO> {
    const filePath = branchContext.getInPath(FEAT_FORGE_GENERATED_SERVICES_FILE);

    if (!(await pathExists(filePath))) {
        throw new ForgeError(`❌ Generated services file not found at ${filePath}. Please run 'forge services scan' first.`);
    }

    try {
        return readJSONFile(GeneratedServicesDTO, filePath);
    } catch (error) {
        throw ForgeError.extend(error, `❌ Failed to load generated services file at ${filePath}`);
    }
}

/**
 * Generate and write .envrc with service environment variables
 */
export async function generateEnvrcFile(
    forgeContext: ForgeContext,
    branchContext: BranchContext,
    services: ServiceDefinitionWithPort[],
): Promise<{ path: string; env: string }> {
    const branchSlug = branchContext.branchNameSlug;
    const proxyEnabled = forgeContext.options.proxy.enabled;
    const proxyPort = forgeContext.options.proxy.port;
    const varPrefix = forgeContext.options.proxy.environmentVariablePrefix;

    const timestamp = new Date().toISOString();

    const lines: string[] = [];

    // Header
    lines.push('# ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY');
    lines.push(`# This file was generated by 'forge env update' at ${timestamp}`);
    lines.push("# Any manual edits will be lost on the next 'forge env update' run");
    lines.push('');

    // Branch configuration
    lines.push('# --------------------');
    lines.push('# Branch configuration');
    lines.push('# --------------------');
    lines.push(`export ${varPrefix}BRANCH_SLUG="${branchSlug}"`);
    lines.push(`export ${varPrefix}BRANCH_SERVICES_CONFIG="${FEAT_FORGE_GENERATED_SERVICES_FILE}"`);
    lines.push('');

    lines.push('# ----------------------');
    lines.push('# Services configuration');
    lines.push('# ----------------------');
    for (const service of services) {
        const { SLUG, port, url, proxyUrl, path } = getServiceOutputs(forgeContext, branchContext, service);
        const envName = `${varPrefix}${SLUG}`;
        lines.push(`export ${envName}_PORT=${port}`);
        lines.push(`export ${envName}_URL=${url}`);
        lines.push(`${proxyEnabled ? '' : '# '}export ${envName}_PROXY_URL=${proxyUrl}`);
        if (path) {
            lines.push(`export ${envName}_PATH="${path}"`);
        }

        lines.push('');
    }

    // Forge proxy configuration (for future use)
    lines.push('# ------------------------------------------');
    lines.push('# Forge proxy configuration (for future use)');
    lines.push('# ------------------------------------------');
    lines.push(`export ${varPrefix}PROXY_ENABLED=${proxyEnabled}`);
    lines.push(`${proxyEnabled ? '' : '# '}export ${varPrefix}PROXY_PORT=${proxyPort}`);
    lines.push('');

    const content = lines.join('\n');

    // Write to file
    const filePath = branchContext.getInPath(forgeContext.options.proxy.envrc);
    await writeTextFile(filePath, content);

    return { path: filePath, env: content };
}

/**
 * Get service output variable values for a service.
 * To be used in .envrc generation or proxy configuration generation.
 */
export function getServiceOutputs(forgeContext: ForgeContext, branchContext: BranchContext, service: ServiceDefinitionWithPort) {
    const serviceSlug = slugify(service.name, false, true); // Don't allow slashes or hyphens in service slug to keep env var names clean
    const urlSlug = slugify(service.name, false);
    const branchSlug = branchContext.branchNameSlug;
    const proxyPort = forgeContext.options.proxy.port;
    return {
        ...service,
        slug: serviceSlug,
        SLUG: serviceSlug.toUpperCase(),
        url: `${service.type}://localhost:${service.port}${service.path || ''}`,
        proxyUrl: `${service.type}://${branchSlug}.${urlSlug}.localhost:${proxyPort}${service.path || ''}`,
    };
}
