import { ShellName } from '../foundation/types/ShellName';

/**
 * Commands for generating shell aliases for feat-forge.
 */
export class AliasCommands {
    /**
     * Generate and print shell aliases for the specified shell.
     */
    generate(shell: ShellName, prefix: string): void {
        let output: string;
        switch (shell) {
            case ShellName.Bash:
                output = this.generateBashAliases(prefix);
                break;
            case ShellName.Zsh:
                output = this.generateZshAliases(prefix);
                break;
            case ShellName.Fish:
                output = this.generateFishAliases(prefix);
                break;
            case ShellName.PowerShell:
            case ShellName.Pwsh:
                output = this.generatePowerShellAliases(prefix);
                break;
            default:
                throw new Error(`Unsupported shell: ${shell}`);
        }
        console.log(output);
    }

    // ============================================================================
    // PRIVATE METHODS
    // ============================================================================

    private generateBashAliases(p: string): string {
        return `# feat-forge aliases (generated by: forge alias bash --prefix ${p})
# Add to your ~/.bashrc:  source <(forge alias bash${p !== 'ff' ? ` --prefix ${p}` : ''})

# Group aliases
alias ${p}='forge'
alias ${p}f='forge feature'
alias ${p}i='forge fix'
alias ${p}r='forge release'

# Command shortcuts
alias ${p}s='forge start'
alias ${p}c='forge create'
alias ${p}o='forge open'
alias ${p}l='forge list'
alias ${p}m='forge merge'
alias ${p}a='forge archive'

# Feature shortcuts
alias ${p}fs='forge feature start'
alias ${p}fc='forge feature create'
alias ${p}fo='forge feature open'
alias ${p}fl='forge feature list'
alias ${p}fm='forge feature merge'
alias ${p}fa='forge feature archive'

# Fix shortcuts
alias ${p}is='forge fix start'
alias ${p}ic='forge fix create'
alias ${p}io='forge fix open'
alias ${p}il='forge fix list'

# Release shortcuts
alias ${p}rs='forge release start'
alias ${p}rc='forge release create'
alias ${p}ro='forge release open'
alias ${p}rl='forge release list'

# cd into branch worktree
${p}cd()  { cd "$(forge path "$@")"; }
${p}fcd() { cd "$(forge feature path "$@")"; }
${p}icd() { cd "$(forge fix path "$@")"; }
${p}rcd() { cd "$(forge release path "$@")"; }
`;
    }

    private generateZshAliases(p: string): string {
        return `# feat-forge aliases (generated by: forge alias zsh --prefix ${p})
# Add to your ~/.zshrc:  source <(forge alias zsh${p !== 'ff' ? ` --prefix ${p}` : ''})

# Group aliases
alias ${p}='forge'
alias ${p}f='forge feature'
alias ${p}i='forge fix'
alias ${p}r='forge release'

# Command shortcuts
alias ${p}s='forge start'
alias ${p}c='forge create'
alias ${p}o='forge open'
alias ${p}l='forge list'
alias ${p}m='forge merge'
alias ${p}a='forge archive'

# Feature shortcuts
alias ${p}fs='forge feature start'
alias ${p}fc='forge feature create'
alias ${p}fo='forge feature open'
alias ${p}fl='forge feature list'
alias ${p}fm='forge feature merge'
alias ${p}fa='forge feature archive'

# Fix shortcuts
alias ${p}is='forge fix start'
alias ${p}ic='forge fix create'
alias ${p}io='forge fix open'
alias ${p}il='forge fix list'

# Release shortcuts
alias ${p}rs='forge release start'
alias ${p}rc='forge release create'
alias ${p}ro='forge release open'
alias ${p}rl='forge release list'

# cd into branch worktree
${p}cd()  { cd "$(forge path "$@")"; }
${p}fcd() { cd "$(forge feature path "$@")"; }
${p}icd() { cd "$(forge fix path "$@")"; }
${p}rcd() { cd "$(forge release path "$@")"; }
`;
    }

    private generateFishAliases(p: string): string {
        return `# feat-forge aliases (generated by: forge alias fish --prefix ${p})
# Add to your ~/.config/fish/config.fish:  forge alias fish${p !== 'ff' ? ` --prefix ${p}` : ''} | source

# Group aliases
abbr -a ${p} forge
abbr -a ${p}f 'forge feature'
abbr -a ${p}i 'forge fix'
abbr -a ${p}r 'forge release'

# Command shortcuts
abbr -a ${p}s 'forge start'
abbr -a ${p}c 'forge create'
abbr -a ${p}o 'forge open'
abbr -a ${p}l 'forge list'
abbr -a ${p}m 'forge merge'
abbr -a ${p}a 'forge archive'

# Feature shortcuts
abbr -a ${p}fs 'forge feature start'
abbr -a ${p}fc 'forge feature create'
abbr -a ${p}fo 'forge feature open'
abbr -a ${p}fl 'forge feature list'
abbr -a ${p}fm 'forge feature merge'
abbr -a ${p}fa 'forge feature archive'

# Fix shortcuts
abbr -a ${p}is 'forge fix start'
abbr -a ${p}ic 'forge fix create'
abbr -a ${p}io 'forge fix open'
abbr -a ${p}il 'forge fix list'

# Release shortcuts
abbr -a ${p}rs 'forge release start'
abbr -a ${p}rc 'forge release create'
abbr -a ${p}ro 'forge release open'
abbr -a ${p}rl 'forge release list'

# cd into branch worktree
function ${p}cd; cd (forge path $argv); end
function ${p}fcd; cd (forge feature path $argv); end
function ${p}icd; cd (forge fix path $argv); end
function ${p}rcd; cd (forge release path $argv); end
`;
    }

    private generatePowerShellAliases(p: string): string {
        return `# feat-forge aliases (generated by: forge alias powershell --prefix ${p})
# Add to your $PROFILE:  forge alias powershell${p !== 'ff' ? ` --prefix ${p}` : ''} | Out-String | Invoke-Expression

# Group functions
function ${p} { forge @args }
function ${p}f { forge feature @args }
function ${p}i { forge fix @args }
function ${p}r { forge release @args }

# Command shortcuts
function ${p}s { forge start @args }
function ${p}c { forge create @args }
function ${p}o { forge open @args }
function ${p}l { forge list @args }
function ${p}m { forge merge @args }
function ${p}a { forge archive @args }

# Feature shortcuts
function ${p}fs { forge feature start @args }
function ${p}fc { forge feature create @args }
function ${p}fo { forge feature open @args }
function ${p}fl { forge feature list @args }
function ${p}fm { forge feature merge @args }
function ${p}fa { forge feature archive @args }

# Fix shortcuts
function ${p}is { forge fix start @args }
function ${p}ic { forge fix create @args }
function ${p}io { forge fix open @args }
function ${p}il { forge fix list @args }

# Release shortcuts
function ${p}rs { forge release start @args }
function ${p}rc { forge release create @args }
function ${p}ro { forge release open @args }
function ${p}rl { forge release list @args }

# cd into branch worktree
function ${p}cd { Set-Location (forge path @args) }
function ${p}fcd { Set-Location (forge feature path @args) }
function ${p}icd { Set-Location (forge fix path @args) }
function ${p}rcd { Set-Location (forge release path @args) }
`;
    }
}
